### ISSUE TITLE
Adding libraries such as "pandas" fails

### ISSUE THREAD

**Issue by barbaros-oezdemir** [IBM/python-flask-app#109]
when i add pandas into Pipfile deployment as CF app succeeds however the app crashes. when i checked the logs i saw that pandas module could not be found. the pipfile seems to be not working properly

**Comment by testrashmi** [comment]
Additional information for the above issue reported by customer:

python to COS connection: ibm_boto3 module not found

Customer is using
https://cloud.ibm.com/developer/appservice/starter-kits
Python Flask App- created an app and let IBM Cloud deploy it on CF and also create a CI/Cd pipeline
He is having an issue with importing libraries to my Python application deployed on public Cloud Foundry
Deployment succeeds, but the application crashes
“i am using ibm_boto3 again:
APP/PROC/WEB 0 [2021-09-14 17:47:18 +0000] [90] [INFO] Listening at: http://0.0.0.0:8080 (90) Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 [2021-09-14 17:47:18 +0000] [90] [INFO] Using worker: sync Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 [2021-09-14 17:47:18 +0000] [101] [INFO] Booting worker with pid: 101 Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 [2021-09-14 17:47:18 +0000] [101] [ERROR] Exception in worker process Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 Traceback (most recent call last): Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 [2021-09-14 17:47:18 +0000] [90] [INFO] Reason: Worker failed to boot. Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 File “/home/vcap/deps/0/python/lib/python3.9/site-packages/gunicorn/arbiter.py”, line 589, in spawn_worker Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 worker.init_process() Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 File “/home/vcap/deps/0/python/lib/python3.9/site-packages/gunicorn/workers/base.py”, line 134, in init_process Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 self.load_wsgi() Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 File “/home/vcap/deps/0/python/lib/python3.9/site-packages/gunicorn/workers/base.py”, line 146, in load_wsgi Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 self.wsgi = self.app.wsgi() Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 File “/home/vcap/deps/0/python/lib/python3.9/site-packages/gunicorn/app/base.py”, line 67, in wsgi Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 self.callable = self.load() Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 File “/home/vcap/deps/0/python/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py”, line 58, in load Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 return self.load_wsgiapp() Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 File “/home/vcap/deps/0/python/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py”, line 48, in load_wsgiapp Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 return util.import_app(self.app_uri) Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 File “/home/vcap/deps/0/python/lib/python3.9/site-packages/gunicorn/util.py”, line 359, in import_app Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 mod = importlib.import_module(module) Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 File “/home/vcap/deps/0/python/lib/python3.9/importlib/__init__.py”, line 127, in import_module Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 return _bootstrap._gcd_import(name[level:], package, level) Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 File “<frozen importlib._bootstrap>“, line 1030, in _gcd_import Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 File “<frozen importlib._bootstrap>“, line 1007, in _find_and_load Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 File “<frozen importlib._bootstrap>“, line 986, in _find_and_load_unlocked Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 File “<frozen importlib._bootstrap>“, line 680, in _load_unlocked Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 File “<frozen importlib._bootstrap_external>“, line 850, in exec_module Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 File “<frozen importlib._bootstrap>“, line 228, in _call_with_frames_removed Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 File “/home/vcap/app/server/__init__.py”, line 7, in <module> Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 from server.routes import * Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 File “/home/vcap/app/server/routes/prodango.py”, line 3, in <module> Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 from .prodangoCode import b, c Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 File “/home/vcap/app/server/routes/prodangoCode.py”, line 1, in <module> Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 import ibm_boto3 Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 ModuleNotFoundError: No module named ‘ibm_boto3’ Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 [2021-09-14 17:47:18 +0000] [101] [INFO] Worker exiting (pid: 101) Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 [2021-09-14 17:47:18 +0000] [90] [INFO] Shutting down: Master Sep 14, 2021, 07:47:18 PM
APP/PROC/WEB 0 Exit status 0 Sep 14, 2021, 07:47:18 PM
CELL/SSHD 0 Exit status 0 Sep 14, 2021, 07:47:18 PM
CELL 0 Cell 171b5a8f-5b32-4986-90b6-5b7476ff6b06 stopping instance feb0657e-6414-4a9c-7fbe-9427 Sep 14, 2021, 07:47:24 PM
CELL 0 Cell 171b5a8f-5b32-4986-90b6-5b7476ff6b06 destroying container for instance feb0657e-6414-4a9c-7fbe-9427 Sep 14, 2021, 07:47:24 PM
API 6 Process has crashed with type: “web”

**Comment by youming-lin** [comment]
@ChuckCox Can you take a look?
